name: My first workflow
on: push
jobs: 
    first_job: 
        runs-on: ubuntu-latest
        steps:
        - name: checkout repo
          uses: actions/checkout@v4

        - name: List and read
          run: |
            echo "my first GitHub Action job"
            ls -ltra
            cat README.md

        - name: generate ASCII artwork
          run: cowsay -f dragon "I am a dragon from new city" >> dragon.txt
        
        # - name: Welcome Page
        #   run: echo "my first GitHub Action job"

        # - name: list files
        #   run: ls -a
        
        # - name: readme file
        #   run: cat README.md