name: Generate ASCII Artwork

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout main
          uses: actions/checkout@v4
        
        - name: Welcome message
          run: |
           echo "This is my ASCII actions"
           ls -ltra
           cat README.md
