name: Multi jobs pipeline

on: 
  push

jobs:
    Build_job_1:
        runs-on: ubuntu-latest
        steps:
        # - name: Checkout main
        #   uses: actions/checkout@v4

        - name: Install cowsay package
          run: |
            sudo apt-get install cowsay -y

        - name: execute cowsay command
          run: cowsay -f dragon "I am a dragon from new city and a NEW DRAGONs ...... Hee..heee...!!!" >> dragon.txt

        - name: Upload artifacts
          uses: actions/upload-artifact@v4
          with:
            name: cowsay artifacts 
            path: dragon.txt

        - name: sleep for 10 seconds
          run: sleep 10

    test_job_2:
        needs: [Build_job_1]
        runs-on: ubuntu-latest
        steps:
        - name: sleep 10 seconds
          run: sleep 10
        
        - name: Download Artifacts
          uses: actions/download-artifact@v4
          with:
            name: dragon file

        - name: test file exists
          run: grep -i "dragon" dragon.txt
   
    deploy_job_3:
        needs: [test_job_2]
        runs-on: ubuntu-latest
        steps:
        - name: Download artifacts
          uses: actions/download-artifact@v4
          with:
            name: dragon file

        - name: Read file
          run: cat dragon.txt
        
        - name: deployment
          run: echo -e "\033[0;33mdeploying ......"
    